language: node_js
node_js:
  - "7"
branches:
  only:
  - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
before_script:
  - npm i -g firebase-tools
script: 
  - yarn run build
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"